environment: test # Will be overridden by ENV

server:
  port: 8080

database:
  host: "localhost"
  dbname: "pavilion_test"  # Test database
  port: 26257
  user: "root"
  password: ""  # Will be overridden by DB_PASSWORD
  sslmode: "disable"
  timezone: "UTC"
  pool:
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 1h

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

ipfs:
  host: "localhost:5001"
  gateway_url: "https://ipfs.io/ipfs/"

logging:
  level: error  # Default to error level for tests
  format: console  # Default to console for better test output
  output: stdout  # Always use stdout for tests
  file:
    enabled: false  # Never use file logging in tests
    path: /var/log/pavilion
    rotate: false
    maxSize: 100MB
    maxAge: 7d
  development: true  # Always true for test environment
  sampling:
    initial: 100  # No sampling in tests
    thereafter: 100

ffmpeg:
  path: "/opt/homebrew/bin/ffmpeg"
  probePath: "/opt/homebrew/bin/ffprobe"
  videoCodec: "libx264"
  audioCodec: "copy"
  preset: "fast"
  hlsTime: 10
  hlsPlaylistType: "vod"
  outputPath: "/tmp/videos"
  resolutions:
    - "720p"
    - "480p"
    - "360p"

# ... other configurations ...

storage:
  uploadDir: "uploads"
  tempDir: "temp"
  ipfs:
    apiAddress: "/ip4/127.0.0.1/tcp/5001"
    gateway: "http://localhost:8080"
  s3:
    endpoint: "s3.amazonaws.com"
    bucket: "octopus-doganbros-storage"
    region: "eu-central-1"
    accessKeyId: ""  # Will be overridden by S3_ACCESS_KEY_ID
    secretAccessKey: ""  # Will be overridden by S3_SECRET_ACCESS_KEY
    useSSL: true
    root_directory: "videos_test"  # Use a separate directory for test files
    directories:
      videoPost: "video-posts/"
      meetingRecording: "meeting-recordings/"
      chatAttachments: "chat-attachments/"
      profilePhoto: "profile-photos/"

video:
  maxSize: 104857600  # 100MB in bytes
  minTitleLength: 3
  maxTitleLength: 100
  maxDescLength: 500
  allowedFormats:
    - ".mp4"
    - ".mov"
    - ".avi"
    - ".webm"

auth:
  jwt:
    secret: test-secret-key  # Will be overridden by JWT_SECRET
    accessTokenTTL: 168h
    refreshTokenTTL: 168h 