environment: ${ENV:-development}  # Can be 'development', 'staging', or 'production'

server:
  port: 8080

database:
  host: "localhost"
  dbname: "pavilion_db"
  port: 26257
  user: "root"
  password: ""
  sslmode: "disable"
  timezone: "UTC"
  pool:
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 1h  # Duration string format: "1h" for 1 hour, "30m" for 30 minutes, etc.

  # Postgres
  # user: "youruser"
  # password: "yourpassword"
  # port: 5432

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

ipfs:
  host: "localhost:5001"
  gateway_url: "https://ipfs.io/ipfs/"

logging:
  level: "debug"

ffmpeg:
  path: "/usr/local/bin/ffmpeg"
  probePath: "/usr/local/bin/ffprobe"
  videoCodec: "libx264"
  audioCodec: "copy"
  preset: "fast"
  hlsTime: 10
  hlsPlaylistType: "vod"

# ... other configurations ...

storage:
  uploadDir: "uploads"
  tempDir: "temp"
  ipfs:
    apiAddress: "/ip4/127.0.0.1/tcp/5001"
    gateway: "http://localhost:8080"
  s3:
    endpoint: "s3.amazonaws.com"
    bucket: "octopus-doganbros-storage"
    region: "eu-central-1"
    accessKeyId: ""
    secretAccessKey: ""
    useSSL: true
    directories:
      videoPost: "video-posts/"
      meetingRecording: "meeting-recordings/"
      chatAttachments: "chat-attachments/"
      profilePhoto: "profile-photos/"

video:
  maxSize: 104857600  # 100MB in bytes
  minTitleLength: 3
  maxTitleLength: 100
  maxDescLength: 500
  allowedFormats:
    - ".mp4"
    - ".mov"
    - ".avi"
    - ".webm"