version: '3.8'
services:
  postgres:
    image: postgres
    container_name: pavilion-postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=pavilion_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pavilion-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80" # Ensure host port 5050 maps to container port 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis
    container_name: pavilion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ipfs:
    image: ipfs/go-ipfs
    container_name: pavilion-ipfs
    ports:
      - "4001:4001" # Swarm port
      - "5001:5001" # API port
      - "8081:8080" # Gateway port
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  pgdata:
  pgadmin_data:
  redis_data:
  ipfs_data:
