services:
  #postgres:
  #  image: postgres
  #  container_name: pavilion-postgres
  #  environment:
  #   - POSTGRES_USER=youruser
  #    - POSTGRES_PASSWORD=yourpassword
  #    - POSTGRES_DB=pavilion_db
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data

  cockroachdb-1:
    image: cockroachdb/cockroach:v22.1.12
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    ports:
      - "26257:26257"
      - "8082:8080"
    volumes:
      - cockroach_data_1:/cockroach/cockroach-data
  cockroachdb-2:
    image: cockroachdb/cockroach:v22.1.12
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    ports:
      - "26258:26257"
      - "8083:8080"
    volumes:
      - cockroach_data_2:/cockroach/cockroach-data
  cockroachdb-3:
    image: cockroachdb/cockroach:v22.1.12
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    ports:
      - "26259:26257"
      - "8084:8080"
    volumes:
      - cockroach_data_3:/cockroach/cockroach-data

  # ScyllaDB Cluster
  scylladb-1:
    image: scylladb/scylla:latest
    container_name: pavilion-scylladb-1
    command: --seeds=scylladb-1,scylladb-2,scylladb-3
    ports:
      - "9042:9042"
    volumes:
      - scylla_data_1:/var/lib/scylla
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  scylladb-2:
    image: scylladb/scylla:latest
    container_name: pavilion-scylladb-2
    command: --seeds=scylladb-1,scylladb-2,scylladb-3
    ports:
      - "9043:9042"
    volumes:
      - scylla_data_2:/var/lib/scylla
    depends_on:
      - scylladb-1
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  scylladb-3:
    image: scylladb/scylla:latest
    container_name: pavilion-scylladb-3
    command: --seeds=scylladb-1,scylladb-2,scylladb-3
    ports:
      - "9044:9042"
    volumes:
      - scylla_data_3:/var/lib/scylla
    depends_on:
      - scylladb-1
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pavilion-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80" # Ensure host port 5050 maps to container port 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis
    container_name: pavilion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ipfs:
    image: ipfs/go-ipfs
    container_name: pavilion-ipfs
    ports:
      - "4001:4001" # Swarm port
      - "5001:5001" # API port
      - "8081:8080" # Gateway port
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  # pgdata:
  cockroach_data_1:
  cockroach_data_2:
  cockroach_data_3:
  scylla_data_1:
  scylla_data_2:
  scylla_data_3:
  pgadmin_data:
  redis_data:
  ipfs_data:
