services:

  cockroachdb-1:
    image: cockroachdb/cockroach:v22.1.12
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8082:8080"
    volumes:
      - cockroach_data_1:/cockroach/cockroach-data

  scylladb:
    image: scylladb/scylla:latest
    container_name: pavilion-scylladb
    ports:
      - "9042:9042" # CQL port
      - "9160:9160" # Thrift port
      - "7010:7000" # Inter-node communication
      - "7011:7001" # SSL inter-node communication
      - "10000:10000" # REST API
    volumes:
      - scylla_data:/var/lib/scylla
    command: --developer-mode=1 --smp 1
    environment:
      - SCYLLA_BATCH_SIZE=128
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: pavilion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pulsar:
    image: apachepulsar/pulsar:2.10.1
    container_name: pavilion-pulsar
    ports:
      - "6650:6650" # Pulsar protocol port
      - "6651:6651" # Pulsar SSL protocol port
      - "8080:8080" # Pulsar web UI port
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m"
    command: >
      /bin/bash -c " bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf
      - ./init-pulsar.sh:/pulsar/init-pulsar.sh
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pulsar-init:
    image: apachepulsar/pulsar:2.10.1
    container_name: pavilion-pulsar-init
    depends_on:
      pulsar:
        condition: service_healthy
    volumes:
      - ./init-pulsar.sh:/pulsar/init-pulsar.sh
    entrypoint: [ "sh", "-c", "chmod +x /pulsar/init-pulsar.sh && /pulsar/init-pulsar.sh" ]

  ipfs:
    image: ipfs/go-ipfs
    container_name: pavilion-ipfs
    ports:
      - "4001:4001" # Swarm port
      - "5001:5001" # API port
      - "8081:8080" # Gateway port
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  # pgdata:
  cockroach_data_1:
  redis_data:
  ipfs_data:
  scylla_data:
  pulsar_data:
  pulsar_conf:
